/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gymassignmentthree;

import javax.swing.JRootPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author davwo
 */
public class jMemberFrame extends javax.swing.JFrame {
    Gym myModel = new Gym();
    Membership membershipType;
    
    /**
     * Creates new form MemberFrame
     */
    public jMemberFrame(Gym myModel) {
        this.myModel = myModel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNameText = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jYearRadio = new javax.swing.JRadioButton();
        j90Radio = new javax.swing.JRadioButton();
        j30Radio = new javax.swing.JRadioButton();
        jAcceptButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameTextActionPerformed(evt);
            }
        });
        jNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNameTextKeyPressed(evt);
            }
        });

        jYearRadio.setText("365 Days ($)");
        jYearRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jYearRadioActionPerformed(evt);
            }
        });

        j90Radio.setText("90 Days ($)");
        j90Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j90RadioActionPerformed(evt);
            }
        });

        j30Radio.setText("30 Day Free Trial");
        j30Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j30RadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jYearRadio)
                    .addComponent(j90Radio)
                    .addComponent(j30Radio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(j30Radio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(j90Radio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jYearRadio)
                .addContainerGap())
        );

        jAcceptButton.setText("Accept");
        jAcceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAcceptButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jAcceptButton)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jAcceptButton)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j30RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j30RadioActionPerformed
        j30Radio.setSelected(true);
        j90Radio.setSelected(false);
        jYearRadio.setSelected(false);
        membershipType = new FreeMonth();
        // TODO add your handling code here:
    }//GEN-LAST:event_j30RadioActionPerformed

    private void j90RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j90RadioActionPerformed
        j30Radio.setSelected(false);
        j90Radio.setSelected(true);
        jYearRadio.setSelected(false);
        membershipType = new ThreeMonths();
        // TODO add your handling code here:
    }//GEN-LAST:event_j90RadioActionPerformed

    private void jYearRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jYearRadioActionPerformed
        j30Radio.setSelected(false);
        j90Radio.setSelected(false);
        jYearRadio.setSelected(true);
        membershipType = new TwelveMonths();
        // TODO add your handling code here:
    }//GEN-LAST:event_jYearRadioActionPerformed

    private void jAcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAcceptButtonActionPerformed
        if((jNameText.getText().length() > 0)&&(membershipType!=null)){
            //Move lines below HERE after testing
        }
        Member myMember= new Member(myModel, jNameText.getText(), membershipType);
        myModel.addMember(myMember);
        dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jAcceptButtonActionPerformed

    private void jNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNameTextActionPerformed

    private void jNameTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNameTextKeyPressed
        JRootPane rootPane = SwingUtilities.getRootPane(jAcceptButton); 
        rootPane.setDefaultButton(jAcceptButton);
        // TODO add your handling code here:
    }//GEN-LAST:event_jNameTextKeyPressed

//    
//    DELETE COMMENT SECTION
//    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(jMemberFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(jMemberFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(jMemberFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(jMemberFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new jMemberFrame().setVisible(true);
//            }
//        });
//    }
//    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton j30Radio;
    private javax.swing.JRadioButton j90Radio;
    private javax.swing.JButton jAcceptButton;
    private javax.swing.JTextField jNameText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jYearRadio;
    // End of variables declaration//GEN-END:variables
}
